# Generated by Django 5.2.1 on 2025-07-23 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('numero_cuenta', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mora_porcentaje', models.IntegerField(choices=[(5, '5%'), (10, '10%'), (15, '15%'), (20, '20%')], default=5)),
                ('dias_sin_recargo', models.IntegerField(choices=[(5, '5 días'), (10, '10 días'), (15, '15 días'), (20, '20 días')], default=5)),
                ('activo', models.BooleanField(default=True)),
                ('banco_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='configuracion.banco')),
            ],
        ),
    ]
