# Generated by Django 5.2.1 on 2025-07-24 20:05

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco',
            options={'ordering': ['-fechaCreacion'], 'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='configuracion',
            options={'ordering': ['-fechaCreacion'], 'verbose_name': 'Configuracion', 'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AddField(
            model_name='banco',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 24, 20, 4, 52, 500491)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
