# Generated by Django 5.2.1 on 2025-07-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_alter_banco_options_alter_configuracion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='banco',
            name='numero_cuenta',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='banco',
            constraint=models.UniqueConstraint(fields=('nombre', 'numero_cuenta'), name='unique_nombre_numero_cuenta'),
        ),
    ]
