# Generated by Django 5.2.1 on 2025-10-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_alter_banco_nombre_alter_banco_numero_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='dias_confirmacion_bancaria',
            field=models.IntegerField(choices=[(3, '3 días'), (5, '5 días'), (8, '8 días')], default=5),
        ),
    ]
