# Generated by Django 5.2.1 on 2025-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_configuracion_dias_confirmacion_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='dias_confirmacion_bancaria',
            field=models.IntegerField(choices=[(3, '3 días'), (5, '5 días'), (8, '8 días')], default=3, help_text='Días para confirmar depósitos bancarios.'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='dias_sin_recargo',
            field=models.IntegerField(choices=[(0, 'Sin días sin recargo'), (5, '5 días'), (10, '10 días'), (15, '15 días'), (20, '20 días')], default=5, help_text='Días sin recargo antes de aplicar mora. Sólo aplica si hay mmora configurada.'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='mora_porcentaje',
            field=models.IntegerField(choices=[(0, 'Sin mora'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%')], default=0, help_text='Porcentaje de mora a aplicar. 0% = Sin mora automática'),
        ),
    ]
