# Generated by Django 5.2.1 on 2025-05-15 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('idEstadoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('nit', models.CharField(blank=True, max_length=15, null=True)),
                ('direccionCompleta', models.CharField(max_length=100)),
                ('telefono1', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{8}$ | ^\\d{4}-\\d{4}$', 'Número inválido. Debe contener 8 dígitos o seguir el formato XXXX-XXXX.')])),
                ('telefono2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$ | ^\\d{4}-\\d{4}$', 'Número inválido. Debe contener 8 dígitos o seguir el formato XXXX-XXXX.')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.estadousuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fechaCreacion'],
            },
        ),
    ]
