# Generated by Django 5.2.1 on 2025-05-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nit',
        ),
        migrations.AddField(
            model_name='usuario',
            name='dpi',
            field=models.CharField(default=12, max_length=15),
            preserve_default=False,
        ),
    ]
