# Generated by Django 5.2.1 on 2025-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_nit_usuario_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nit',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
