# Generated by Django 5.2.1 on 2025-05-15 18:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLocal',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idUbicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('idNivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locales.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('idLocal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locales.estadolocal')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.negocio')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.nivel')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.ubicacion')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['-fechaCreacion'],
            },
        ),
    ]
