# Generated by Django 5.2.1 on 2025-06-04 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
        ('negocios', '0002_alter_negocio_telefono1_alter_negocio_telefono2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='negocio',
        ),
        migrations.CreateModel(
            name='OcupacionLocal',
            fields=[
                ('idOcupacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupaciones', to='locales.local')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.negocio')),
            ],
        ),
    ]
