# Generated by Django 5.2.1 on 2025-06-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_remove_local_negocio_ocupacionlocal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='ubicacion',
        ),
    ]
