# Generated by Django 5.2.1 on 2025-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_remove_local_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='posicionMapa',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de posición en el mapa visual (1 a 8)', null=True, unique=True),
        ),
    ]
