# Generated by Django 5.2.1 on 2025-07-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0004_local_posicionmapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocupacionlocal',
            options={'ordering': ['-idOcupacion'], 'verbose_name': 'OcupacionLocal', 'verbose_name_plural': 'OcupacionLocales'},
        ),
    ]
