# Generated by Django 5.2.1 on 2025-11-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0005_alter_ocupacionlocal_options'),
        ('negocios', '0003_alter_negocio_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locales.nivel'),
        ),
        migrations.AddConstraint(
            model_name='ocupacionlocal',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('local', 'negocio'), name='uniq_ocupacion_activa_por_local_y_negocio'),
        ),
    ]
