# Generated by Django 5.2.1 on 2025-07-28 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boletas', '0007_alter_boletasandbox_comentarios_validacion_and_more'),
        ('negocios', '0003_alter_negocio_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('idTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(editable=False, max_length=120, unique=True)),
                ('fechaTransaccion', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADA', 'Procesada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('boleta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='boletas.boleta')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.negocio')),
            ],
        ),
    ]
