# Generated by Django 5.2.1 on 2025-05-15 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boletas', '0001_initial'),
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTransaccion',
            fields=[
                ('idEstadoTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('idTransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(editable=False, max_length=120, unique=True)),
                ('fechaTransaccion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('boleta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='boletas.boleta')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transacciones.estadotransaccion')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fechaTransaccion'],
            },
        ),
    ]
