# Generated by Django 5.2.1 on 2025-08-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada'), ('fallida', 'Fallida')], default='PENDIENTE', max_length=20),
        ),
    ]
