# Generated by Django 5.2.1 on 2025-08-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='periodo_pagado',
            field=models.CharField(default=2025, help_text='Formato: YYYY-MM', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada'), ('exitosa', 'Exitosa'), ('fallida', 'Fallida')], default='pendiente', max_length=20),
        ),
    ]
