# Generated by Django 5.2.1 on 2025-08-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_transaccion_periodo_pagado_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fechaTransaccion'], 'verbose_name': 'Transaccion', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AddField(
            model_name='transaccion',
            name='dias_retraso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='excedente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='faltante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='mora_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pendiente_confirmacion', 'Pendiente de Confirmación'), ('procesada', 'Procesada'), ('exitosa', 'Exitosa'), ('fallida', 'Fallida')], default='pendiente', max_length=25),
        ),
    ]
