# Generated by Django 5.2.1 on 2025-08-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_alter_transaccion_options_transaccion_dias_retraso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha_limite_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
