# Generated by Django 5.2.1 on 2025-08-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_transaccion_fecha_limite_confirmacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha_ingreso_sistema',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
