# Generated by Django 5.2.1 on 2025-08-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0006_transaccion_fecha_ingreso_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='mensaje_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('espera_confirmacion', 'En espera de confirmación de fondos'), ('espera_complemento', 'Espera de complemento de pago'), ('espera_acreditacion', 'Espera de acreditación de saldo a favor'), ('procesada', 'Procesada'), ('exitosa', 'Exitosa'), ('rechazada', 'Rechazada'), ('fallida', 'Fallida')], default='pendiente', max_length=45),
        ),
    ]
