# Generated by Django 5.2.1 on 2025-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0007_transaccion_mensaje_final_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('espera_confirmacion', 'En espera de confirmación de fondos'), ('espera_confirmacion_faltante', 'En espera de confirmación - Con faltante'), ('espera_complemento', 'Espera de complemento de pago'), ('espera_acreditacion', 'Espera de acreditación de saldo a favor'), ('procesada', 'Procesada'), ('exitosa', 'Exitosa'), ('rechazada', 'Rechazada'), ('fallida', 'Fallida')], default='pendiente', max_length=45),
        ),
    ]
