# Generated by Django 5.2.1 on 2025-11-19 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0006_alter_local_nivel_and_more'),
        ('transacciones', '0008_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='ocupacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='locales.ocupacionlocal'),
        ),
    ]
