# Generated by Django 5.2.1 on 2025-05-15 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locales', '0001_initial'),
        ('negocios', '0001_initial'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLocal',
            fields=[
                ('fechaModificacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('accion', models.CharField(choices=[('CREACION', 'creación'), ('ACTUALIZACION', 'actualización'), ('ELIMINACION', 'eliminación'), ('CAMBIO', 'cambio')], max_length=20)),
                ('tipoCambio', models.CharField(max_length=50)),
                ('estadoAnterior', models.CharField(blank=True, max_length=15, null=True)),
                ('estadoNuevo', models.CharField(blank=True, max_length=15, null=True)),
                ('idHistorialLocal', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.local')),
            ],
            options={
                'ordering': ['-fechaModificacion'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialNegocio',
            fields=[
                ('fechaModificacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('accion', models.CharField(choices=[('CREACION', 'creación'), ('ACTUALIZACION', 'actualización'), ('ELIMINACION', 'eliminación'), ('CAMBIO', 'cambio')], max_length=20)),
                ('tipoCambio', models.CharField(max_length=50)),
                ('estadoAnterior', models.CharField(blank=True, max_length=15, null=True)),
                ('estadoNuevo', models.CharField(blank=True, max_length=15, null=True)),
                ('idHistorialNegocio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio')),
            ],
            options={
                'ordering': ['-fechaModificacion'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialTransaccion',
            fields=[
                ('fechaModificacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('accion', models.CharField(choices=[('CREACION', 'creación'), ('ACTUALIZACION', 'actualización'), ('ELIMINACION', 'eliminación'), ('CAMBIO', 'cambio')], max_length=20)),
                ('tipoCambio', models.CharField(max_length=50)),
                ('estadoAnterior', models.CharField(blank=True, max_length=15, null=True)),
                ('estadoNuevo', models.CharField(blank=True, max_length=15, null=True)),
                ('idHistorialTransaccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacciones.transaccion')),
            ],
            options={
                'ordering': ['-fechaModificacion'],
                'abstract': False,
            },
        ),
    ]
