# Generated by Django 5.2.1 on 2025-10-01 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0001_initial'),
        ('negocios', '0003_alter_negocio_usuario'),
        ('transacciones', '0008_alter_transaccion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPagoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagos_realizados', models.IntegerField(default=0)),
                ('total_monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('promedio_monto_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dia_promedio_pago', models.IntegerField(blank=True, help_text='Día promedio del mes en que realiza el pago (1-31)', null=True)),
                ('mes_con_mas_pagos', models.CharField(blank=True, max_length=20, null=True)),
                ('total_pago_efectivo', models.IntegerField(default=0)),
                ('total_pago_cheque', models.IntegerField(default=0)),
                ('total_pago_deposito', models.IntegerField(default=0)),
                ('metodo_preferido', models.CharField(blank=True, max_length=50, null=True)),
                ('porcentaje_metodo_preferido', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_veces_con_mora', models.IntegerField(default=0)),
                ('total_mora_pagada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promedio_dias_retraso', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_puntualidad', models.DecimalField(decimal_places=2, default=100.0, help_text='Porcentaje de pagos realizados sin mora', max_digits=5)),
                ('racha_actual_sin_mora', models.IntegerField(default=0, help_text='Pagos consecutivos sin mora')),
                ('racha_maxima_sin_mora', models.IntegerField(default=0)),
                ('total_pagos_completos', models.IntegerField(default=0)),
                ('total_pagos_con_faltante', models.IntegerField(default=0)),
                ('total_pagos_con_excedente', models.IntegerField(default=0)),
                ('total_excedente_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('primer_pago', models.DateField(blank=True, null=True)),
                ('ultimo_pago', models.DateField(blank=True, null=True)),
                ('meses_como_cliente', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Pago',
                'verbose_name_plural': 'Perfiles de Pago',
            },
        ),
        migrations.AlterModelOptions(
            name='historialtransaccion',
            options={'ordering': ['-fechaModificacion'], 'verbose_name': 'Historial de Transaccion', 'verbose_name_plural': 'Historiales de Transacciones'},
        ),
        migrations.AddField(
            model_name='historialtransaccion',
            name='dias_retraso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historialtransaccion',
            name='metodo_pago',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialtransaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialtransaccion',
            name='monto_mora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historialtransaccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialtransaccion',
            name='periodo_pagado',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialtransaccion',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='transacciones.transaccion'),
        ),
        migrations.AddIndex(
            model_name='historialtransaccion',
            index=models.Index(fields=['transaccion', '-fechaModificacion'], name='historiales_transac_e033c9_idx'),
        ),
        migrations.AddIndex(
            model_name='historialtransaccion',
            index=models.Index(fields=['periodo_pagado'], name='historiales_periodo_9f4b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='historialtransaccion',
            index=models.Index(fields=['metodo_pago'], name='historiales_metodo__f9503a_idx'),
        ),
        migrations.AddField(
            model_name='perfilpagonegocio',
            name='negocio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_pago', to='negocios.negocio'),
        ),
    ]
