# Generated by Django 5.2.1 on 2025-10-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0002_perfilpagonegocio_alter_historialtransaccion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiallocal',
            name='estadoAnterior',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historiallocal',
            name='estadoNuevo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialnegocio',
            name='estadoAnterior',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialnegocio',
            name='estadoNuevo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estadoAnterior',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estadoNuevo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
