# Generated by Django 5.2.1 on 2025-10-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiales', '0003_alter_historiallocal_estadoanterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiallocal',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'creación'), ('ACTUALIZACION', 'actualización'), ('ELIMINACION', 'eliminación'), ('CAMBIO', 'cambio')], max_length=25),
        ),
        migrations.AlterField(
            model_name='historiallocal',
            name='estadoAnterior',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='historiallocal',
            name='estadoNuevo',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='historiallocal',
            name='tipoCambio',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='historialnegocio',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'creación'), ('ACTUALIZACION', 'actualización'), ('ELIMINACION', 'eliminación'), ('CAMBIO', 'cambio')], max_length=25),
        ),
        migrations.AlterField(
            model_name='historialnegocio',
            name='estadoAnterior',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='historialnegocio',
            name='estadoNuevo',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='historialnegocio',
            name='tipoCambio',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='historialtransaccion',
            name='accion',
            field=models.CharField(choices=[('CREACION', 'creación'), ('ACTUALIZACION', 'actualización'), ('ELIMINACION', 'eliminación'), ('CAMBIO', 'cambio')], max_length=25),
        ),
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estadoAnterior',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='historialtransaccion',
            name='estadoNuevo',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='historialtransaccion',
            name='tipoCambio',
            field=models.CharField(max_length=80),
        ),
    ]
