# Generated by Django 5.2.1 on 2025-05-15 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBoleta',
            fields=[
                ('idEstadoBoleta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('idTipoPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(editable=False, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='boletas/')),
                ('mensajeCorreo', models.TextField()),
                ('monto', models.CharField(max_length=10)),
                ('numeroBoleta', models.CharField(max_length=20)),
                ('numeroDeCuenta', models.CharField(max_length=20)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.negocio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletas.estadoboleta')),
                ('tipoPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boletas.tipopago')),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'ordering': ['-fechaIngreso'],
            },
        ),
    ]
