# Generated by Django 5.2.1 on 2025-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='asunto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='boleta',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='origen',
            field=models.CharField(choices=[('email', 'Correo electrónico'), ('manual', 'Carga Manual')], default='email', max_length=10),
        ),
    ]
