# Generated by Django 5.2.1 on 2025-07-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0002_boleta_asunto_boleta_metadata_boleta_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaSandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.EmailField(max_length=254)),
                ('asunto', models.CharField(blank=True, max_length=255)),
                ('mensaje', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sandbox_boletas/')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('es_valida', models.BooleanField(default=False)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('procesado', models.BooleanField(default=False)),
            ],
        ),
    ]
