# Generated by Django 5.2.1 on 2025-07-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0003_boletasandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletasandbox',
            name='comentarios_validacion',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletasandbox',
            name='estado_validacion',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
