# Generated by Django 5.2.1 on 2025-07-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0004_boletasandbox_comentarios_validacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletasandbox',
            name='comentarios_validacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='boletasandbox',
            name='estado_validacion',
            field=models.CharField(max_length=20),
        ),
    ]
