# Generated by Django 5.2.1 on 2025-07-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0005_alter_boletasandbox_comentarios_validacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletasandbox',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
