# Generated by Django 5.2.1 on 2025-07-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0006_boletasandbox_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletasandbox',
            name='comentarios_validacion',
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name='boletasandbox',
            name='estado_validacion',
            field=models.CharField(max_length=30),
        ),
    ]
