# Generated by Django 5.2.1 on 2025-08-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0007_alter_boletasandbox_comentarios_validacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='fechaCorreoIngresoOriginal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boletasandbox',
            name='estado_validacion',
            field=models.CharField(choices=[('exitosa', 'Exitosa'), ('rechazada', 'Rechazada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=30),
        ),
    ]
