# Generated by Django 5.2.1 on 2025-08-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0008_boleta_fechacorreoingresooriginal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='fechaCorreoIngresoOriginal',
        ),
        migrations.AddField(
            model_name='boleta',
            name='es_complemetaria',
            field=models.BooleanField(default=False),
        ),
    ]
