# Generated by Django 5.2.1 on 2025-08-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0009_remove_boleta_fechacorreoingresooriginal_and_more'),
        ('configuracion', '0003_alter_banco_nombre_alter_banco_numero_cuenta_and_more'),
        ('negocios', '0003_alter_negocio_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='numeroDeCuenta',
        ),
        migrations.AddField(
            model_name='boleta',
            name='banco',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.PROTECT, to='configuracion.banco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='fechaDeposito',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='boleta',
            constraint=models.UniqueConstraint(fields=('banco', 'numeroBoleta'), name='unique_banco_boleta'),
        ),
    ]
