# Generated by Django 5.2.1 on 2025-09-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0010_remove_boleta_numerodecuenta_boleta_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletasandbox',
            name='fecha_procesada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boletasandbox',
            name='hash_image',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='boletasandbox',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boletasandbox',
            name='estado_validacion',
            field=models.CharField(choices=[('exitosa', 'Exitosa'), ('rechazada', 'Rechazada'), ('pendiente', 'Pendiente'), ('duplicada', 'Posible Duplicado')], default='pendiente', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='boletasandbox',
            constraint=models.UniqueConstraint(fields=('message_id',), name='unique_message_id'),
        ),
        migrations.AddConstraint(
            model_name='boletasandbox',
            constraint=models.UniqueConstraint(fields=('remitente', 'hash_image'), name='unique_remitente_hash'),
        ),
    ]
