# Generated by Django 5.2.1 on 2025-09-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0011_boletasandbox_fecha_procesada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletasandbox',
            name='estado_validacion',
            field=models.CharField(choices=[('exitosa', 'Exitosa'), ('rechazada', 'Rechazada'), ('pendiente', 'Pendiente'), ('duplicada', 'Posible Duplicado'), ('procesada', 'Procesada')], default='pendiente', max_length=30),
        ),
    ]
