# Generated by Django 5.2.1 on 2025-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0012_alter_boletasandbox_estado_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletasandbox',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminacion programada'),
        ),
    ]
