# Generated by Django 5.2.1 on 2025-09-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0013_boletasandbox_fecha_eliminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletasandbox',
            name='estado_validacion',
            field=models.CharField(choices=[('exitosa', 'Exitosa'), ('rechazada', 'Rechazada'), ('pendiente', 'Pendiente'), ('duplicada', 'Posible Duplicado'), ('procesada', 'Procesada'), ('sin_imagen', 'Sin Imagen')], default='pendiente', max_length=30),
        ),
    ]
