# Generated by Django 5.2.1 on 2025-12-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0014_alter_boletasandbox_estado_validacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='tipoPago',
            field=models.CharField(choices=[('definir', 'Por Definir'), ('exterior', 'Cheque Exterior'), ('ajeno', 'Cheque Ajeno'), ('propio', 'Cheque Propio'), ('efectivo', 'Efectivo')], default='definir', max_length=15),
        ),
    ]
