# Generated by Django 5.2.1 on 2025-12-12 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0015_alter_boleta_tipopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='tipoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boletas.tipopago'),
        ),
    ]
