# Generated by Django 5.2.1 on 2025-05-15 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRecibo',
            fields=[
                ('idEstadoRecibo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('idRecibo', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('correlativo', models.CharField(max_length=20)),
                ('nombre', models.CharField(editable=False, max_length=110)),
                ('email', models.EmailField(max_length=254)),
                ('fechaGeneracion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='recibos/')),
                ('enviado', models.BooleanField(default=False)),
                ('fechaEnvio', models.DateTimeField(blank=True, null=True)),
                ('mensajeEnvio', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recibos.estadorecibo')),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='transacciones.transaccion')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-fechaGeneracion'],
            },
        ),
    ]
