# Generated by Django 5.2.1 on 2025-05-15 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoNegocio',
            fields=[
                ('idEstadoNegocio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('idNegocio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono1', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{8}$ | ^\\d{4}-\\d{4}$', 'Número inválido. Debe contener 8 dígitos o seguir el formato XXXX-XXXX.')])),
                ('telefono2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$ | ^\\d{4}-\\d{4}$', 'Número inválido. Debe contener 8 dígitos o seguir el formato XXXX-XXXX.')])),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.categoria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.estadonegocio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['-fechaCreacion'],
            },
        ),
    ]
