# Generated by Django 5.2.1 on 2025-05-22 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='telefono1',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(?:\\d{8}|\\d{4}-\\d{4})$', 'Número inválido. Debe contener 8 dígitos o seguir el formato XXXX-XXXX.')]),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='telefono2',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^(?:\\d{8}|\\d{4}-\\d{4})$', 'Número inválido. Debe contener 8 dígitos o seguir el formato XXXX-XXXX.')]),
        ),
    ]
