# Generated by Django 5.2.1 on 2025-07-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_alter_negocio_telefono1_alter_negocio_telefono2'),
        ('usuarios', '0005_usuario_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
