"""
Django settings for sistema_boleta project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.conf import settings
from django.conf.urls.static import static
from decouple import config
import os
import logging

# ================================
# CONFIGURACIÓN DE LOGIN SEGURO
# ================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'email_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/email_security.log',
            'maxBytes': 5 * 1024 * 1024,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'email_security': {
            'handlers': ['email_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ==========================================================
# CONFIGURACION IMAP (ENTRADA)
# ==========================================================

IMAP_SERVER = config("IMAP_SERVER", default="imap.gmail.com")
IMAP_PORT = config("EMAIL_PORT", cast=int, default=993)
IMAP_USE_SSL = True

# Credenciales (Usar app password)
EMAIL_USERNAME = config("EMAIL_USERNAME")
EMAIL_PASSWORD = config("EMAIL_PASSWORD")

# Importante: No imprimir credenciales en produccion
if not config("DEBUG", default=False, cast=bool):
    print("Configuración IMAP cargada")
else:
    # Solo en desarrollo mostrar servidor 
    print(f"[DEV] Servidor IMAP: {IMAP_SERVER}:{IMAP_PORT}")


# =============================================================
# ------ CONFIGURACION SMTP (SALIDA) ------------
# =============================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config("SMTP_SERVER", default="smtp.gmail.com")
EMAIL_PORT = config("SMTP_PORT", cast=int, default=465)
EMAIL_USE_SSL = config("SMTP_USE_SSL", cast=bool, default=True)
EMAIL_USE_TLS = config("SMTP_USE_TLS", cast=bool, default=False)
EMAIL_HOST_USER = config("EMAIL_USERNAME")
EMAIL_HOST_PASSWORD = config("EMAIL_PASSWORD") 
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="EMAIL_HOST_USER")

# Timeout para conexiones SMTP
EMAIL_TIMEOUT = 30

if not config("DEBUG", default=False, cast=bool):
    print("Configuración SMTP cargada")
else:
    print(f"[DEV] Servidor SMTP: {EMAIL_HOST}:{EMAIL_PORT}")


# ===============================================================
# CONFIGURACIÓN DE SEGURIDAD DE EMAIL
# ===============================================================

# Límite de intentos de conexión (protección contra fuerza bruta)
EMAIL_MAX_ATTEMPTS = 5

# Tamaño máximo de archivos adjuntos (5MB)
MAX_EMAIL_ATTACHMENT_SIZE = 5 * 1024 * 1024

# Límite de correos a procesar por ejecución
MAX_EMAILS_PER_RUN = 50


# ================================================================
# VALIDACIÓN DE CONFIGURACIÓN
# ================================================================

def validar_configuracion_email():
    """
    Valida que la configuracion de email sea correcta y segura.
    Se ejecuta al iniciar la aplicación.
    """

    errores = []
    advertencias = []

    # Verificar que SSL esté habilitado
    if not IMAP_USE_SSL:
        advertencias.append("IMAP SSL esté deshabilitado - conexión insegura.")

    if not EMAIL_USE_SSL and not EMAIL_USE_TLS:
        advertencias.append(" SMTP sin SSL/TLS - conexión insegura.")

    # Verificar credenciales
    if not EMAIL_USERNAME or not EMAIL_PASSWORD:
        errores.append("Credenciales de email no configuradas.")

    # Verificar App password 
    if 'gmail.com' in IMAP_SERVER.lower():
        if len(EMAIL_PASSWORD) < 16:
            advertencias.append(
                "La contrasena parece ser real, no APP password. "
                "Se recomienda usar App password de gmail para mayor seguridad."
            )

    # Verificar puertos seguros
    if IMAP_PORT not in [993, 143]:
        advertencias.append(f"Puerto IMAP inusual: {IMAP_PORT}")

    if EMAIL_PORT not in [465, 587]:
        advertencias.append(f"Puerto SMTP inusual: {EMAIL_PORT}")

    # Mostrar resultados
    if errores:
        for error in errores:
            print(error)
        raise Exception("Configuración de Email invalida")
    
    if advertencias and config("DEBUG", default=False, cast=bool):
        for advertencia in advertencias:
            print(advertencia)

    print("Configuracion de email validada")


# Ejecutar validacion al importar settings
try:
    validar_configuracion_email()
except Exception as e:
    if not config("DEBUG", default=False, cast=bool):
        # En produccion, logear pero no detener la aplicacion
        logging.error(f"Error de configuración de email: {e}")
    else:
        # En desarrollo, mostrar el error
        raise


# ============================================================    

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# URL Patterns
urlpatterns = [

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!ee^b*&l(_@^fg34j7i##+654)hjxxm18e$a%$962v%r7bny6r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'negocios',
    'boletas',
    'transacciones',
    'recibos',
    'historiales',
    'locales',
    'core',
    'administracion',
    'configuracion',
    'reportes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_boleta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_boleta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "tickets",
        "USER": "postgres",
        "PASSWORD": config("BD_PASSWORD"),
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Guatemala'

USE_I18N = True

USE_TZ = False

USE_L10N = True

DATE_FORMAT = 'd/m/Y'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    #BASE_DIR / "static",
    #'/var/www/static/',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirecciones automáticas de login/logout
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/'