"""
Django settings for sistema_boleta project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import logging

# ================================
# CONFIGURACIÓN DE LOGIN SEGURO
# ================================

logger = logging.getLogger("email_security")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'email_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'email_security.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'email_security': {
            'handlers': ['email_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ==========================================================
# CONFIGURACION IMAP (ENTRADA)
# ==========================================================

IMAP_SERVER = config("IMAP_SERVER", default="imap.gmail.com")
IMAP_PORT = config("EMAIL_PORT", cast=int, default=993)
IMAP_USE_SSL = True

# Credenciales (Usar app password)
EMAIL_USERNAME = config("EMAIL_USERNAME")
EMAIL_PASSWORD = config("EMAIL_PASSWORD")

# Importante: No imprimir credenciales en produccion
if not DEBUG:
    logger.info("Configuración IMAP cargada")
else:
    # Solo en desarrollo mostrar servidor 
    logger.info(f"[DEV] Servidor IMAP: {IMAP_SERVER}:{IMAP_PORT}")


# =============================================================
# ------ CONFIGURACION SMTP (SALIDA) ------------
# =============================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config("SMTP_SERVER", default="smtp.gmail.com")
EMAIL_PORT = config("SMTP_PORT", cast=int, default=465)
EMAIL_USE_SSL = config("SMTP_USE_SSL", cast=bool, default=True)
EMAIL_USE_TLS = config("SMTP_USE_TLS", cast=bool, default=False)
EMAIL_HOST_USER = config("EMAIL_USERNAME")
EMAIL_HOST_PASSWORD = config("EMAIL_PASSWORD") 
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)

# Timeout para conexiones SMTP
EMAIL_TIMEOUT = 30

if not DEBUG:
    logger.info("Configuración SMTP cargada")
else:
    logger.info(f"[DEV] Servidor SMTP: {EMAIL_HOST}:{EMAIL_PORT}")


# ============================================================    

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'negocios',
    'boletas.apps.BoletasConfig',
    'transacciones',
    'recibos',
    'historiales',
    'locales',
    'core',
    'administracion',
    'configuracion',
    'reportes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_boleta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_boleta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config('POSTGRES_DB', default='tickets'),
        "USER": config('POSTGRES_USER', default='postgres'),
        "PASSWORD": config("POSTGRES_PASSWORD"),
        "HOST": config('POSTGRES_HOST', default='127.0.0.1'),
        "PORT": config('POSTGRES_PORT', default='5432'),
    } 
}

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

IS_DOCKER = config('DJANGO_DOCKER', default=False, cast=bool)

STATIC_URL = '/static/'

if IS_DOCKER:
    STATIC_ROOT = '/app/staticfiles'
    MEDIA_ROOT = '/app/media'
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = '/media/'

if IS_DOCKER:
    logging.basicConfig(level=logging.DEBUG)
    logger = logging.getLogger(__name__)
    logger.info(f"🐳 DJANGO_DOCKER={IS_DOCKER}")
    logger.info(f"📁 MEDIA_ROOT={MEDIA_ROOT}")
    logger.info(f"📂 STATIC_ROOT={STATIC_ROOT}")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Guatemala'

USE_I18N = True

USE_TZ = False

USE_L10N = True

DATE_FORMAT = 'd/m/Y'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATICFILES_DIRS = [
    #BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirecciones automáticas de login/logout
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/'